### ISSUE TITLE
Resize toolbar icons according to DE's font DPI

### ISSUE THREAD

**Issue by kauedg** [mdrasmus/keepnote#743]
When using high-resolution displays (Retina, 4k and such) most users change the desktop environment's font DPI and scale the displays. Keepnote's toolbar icons remain very small after these configurations are made. It would be nice if there were preference parameters or that the app's icons would read the DE's preferences to resize it's icons.

![keepnote toolbar](https://user-images.githubusercontent.com/31520323/41071002-29a6acb8-69cc-11e8-80ab-9b9c95b7f3ec.png)

My settings:
Kubuntu 18.04
KDE Plasma version 5.12.5
Qt version 5.9.5
Kernel 4.15.0-22-generic

Scaling:
Settings -> Fonts -> Force font DPI (211)
Settings -> Display -> Scale (1.7x)

**Comment by vincentcox** [comment]
How did you manage to fix this?
